# fly.toml app configuration file generated for aged-voice-6835 on 2023-07-12T19:34:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-voice-6835"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
